---
version: "2.1"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${FLARESOLVER_LOG_LEVEL:-info}
      - LOG_HTML=${FLARESOLVER_LOG_HTML:-false}
      - CAPTCHA_SOLVER=${FLARESOLVER_CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${FLARESOLVER_PORT:-8191}:8191"
    restart: unless-stopped
